### PR TITLE
Move to store data under app directory 

### LINKED ISSUE #161: [FEATURE REQUEST] Move cache, settings and logs to system location
**Is your feature request related to a problem? Please describe.**
Move the cache, settings and log files to a system location under the users directory

**Describe the solution you'd like**
This needs to be done if we want to move toward a pypi package. Otherwise the user will need to always run the script in the same directory everyday

**Describe alternatives you've considered**
Just need to decide on where it will be stored in the users system. 
This will be where any data related to running of the scripts should be kept in future. i.e. settings, cache, logs etc

### PR DESCRIPTION
**Pull request by cullzie**
# Description

Moved to store data in the users dir (settings, cache and logs). 
Not sure how this will work on windows though. Would need a volunteer to test it out :smile: 

Fixes #161 

## Type of change
This would be a breaking change as we will need to generate the settings and cache again. 

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Works fine in Ubuntu. Data is all stored under the apps folder

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have added tests that prove my fix is effective or that my feature works (Optional)
- [x] New and existing unit tests pass locally with my changes (Optional)

### CODE REVIEW

**Comment by fakeid30** [comment]
```
✖ 1 Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE git:(develop) ↑2 ❯❯❯ python udemy_enroller.py --browser=ff --max-pages=10
Loading existing settings
[WDM] - Driver [/home/nirjhor/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
tutorialbar scraper is running
comidoc scraper is running
Page: 1 of 642 scraped from tutorialbar.com
Got 12 links from https://www.tutorialbar.com in 3.91 seconds
Closing browser
Traceback (most recent call last):
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/udemy_enroller.py", line 120, in <module>
    main()
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/udemy_enroller.py", line 116, in main
    run(args.browser, tutorialbar_enabled, comidoc_enabled, args.max_pages)
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/udemy_enroller.py", line 57, in run
    redeem_courses(dm.driver, settings, tutorialbar_enabled, comidoc_enabled, max_pages)
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/runner.py", line 89, in redeem_courses
    _redeem_courses(driver, settings, scrapers)
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/runner.py", line 36, in _redeem_courses
    udemy_course_links = loop.run_until_complete(scrapers.run())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/scrapers/manager.py", line 28, in run
    await asyncio.gather(*map(lambda sc: sc.run(), enabled_scrapers)),
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/scrapers/base_scraper.py", line 65, in wrapper
    response = await func(self)
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/scrapers/comidoc.py", line 52, in run
    return await self.get_links()
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/scrapers/comidoc.py", line 57, in get_links
    data = await self.get_data()
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/scrapers/comidoc.py", line 93, in get_data
    data = await response.json()
  File "/home/nirjhor/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://comidoc.net/beta')

```

getting this error

**Comment by cullzie** [comment]
That error is not related to these change. It is a http error when connecting to comidoc (Usually when the internet connection is not stable). We'll need to handle this separately. Was going to have it retry and set the scraper to a failed state if its still not successful

**Comment by fakeid30** [comment]
@cullzie hmm these changes run if I disable comidoc via argument. Tested on windows as well. Feel free to merge this. (I forgot to take note on where it is generating files on windows though).

**Comment by cullzie** [comment]
Ye based on your error above the connection issue is to Comidoc. We'll need to add some error handling to the individual scrapers so that failures get isolated to just them and don't cause the whole script to error out

**Comment by fakeid30** [comment]
I would hazard a guess that it's the reason CI is failing . If you run the CI with comidoc disabled , it won't fail. 

I think removing the hardcoded api from the source caused this issue.

**Comment by cullzie** [comment]
> I would hazard a guess that it's the reason CI is failing . If you run the CI with comidoc disabled , it won't fail.
> 
> I think removing the hardcoded api from the source caused this issue.

Changing to the dynamic key was to fix an error due to a change in their API. Seems like it has changed again since that change. It might need to be removed from available scrapers for the time being if the API is changing often

**Pull request merged**
