### PR TITLE
Basic caching structure

### PR DESCRIPTION
**Pull request by cullzie**
PR for issue #83 

Adding basic file cache to improve speed at which we go through pages.
Please test thoroughly :smile:

### CODE REVIEW

**Comment by fakeid30** [comment]
if we merge this now PR #97 will break again , either you or V has to resubmit, since we made him resubmit once, he may be supremely annoyed now.

**Comment by cullzie** [comment]
> if we merge this now PR #97 will break again , either you or V has to resubmit, since we made him resubmit once, he may be supremely annoyed now.

Look at V's changes first. I can change this to a draft until then :+1:

**Comment by fakeid30** [comment]
> Look at V's changes first. I can change this to a draft until then +1

V's change needs a little resolving first , I don't think I should handle it since it's around your code.

**Comment by cullzie** [comment]
> > Look at V's changes first. I can change this to a draft until then +1
> 
> V's change needs a little resolving first , I don't think I should handle it since it's around your code.

@fakeid30 Ye sure I'll have a look. It will be tomorrow at some point though before I can fully test it

**Comment by fakeid30** [comment]
> @fakeid30 Ye sure I'll have a look. It will be tomorrow at some point though before I can fully test it

Fine by me. Massive thanks

**Review by fakeid30 — APPROVED** [review]

**Pull request merged**
