### PR TITLE
add for enroll free course

### PR DESCRIPTION
**Pull request by marain87**
# Description

add for enrolling Free course which enroll page without add to cart button and no need coupon 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [ ] enrolling Free course links which enroll page without add to cart button and no need coupon

### CODE REVIEW

**Comment by cullzie** [comment]
Thanks for contributing @marain87 

I think we had a discussion on this before @fakeid30 where we don't want to enroll in always free courses since you can just get them at anytime. 

Is that what this is adding in?

**Comment by marain87** [comment]
Yes. It is used to enroll always free courses.

**Comment by fakeid30** [comment]
> 
> 
> Thanks for contributing @marain87
> 
> I think we had a discussion on this before @fakeid30 where we don't want to enroll in always free courses since you can just get them at anytime.
> 
> Is that what this is adding in?

Do you think we should add this functionality in?

**Comment by cullzie** [comment]
@fakeid30 I'm not against adding it in although `PAID UDEMY COURSES, ABSOLUTELY FREE!` tag isn't true then. I'll wait until after I release though before looking into it more. Don't want to have anymore noise

**Review by devarshishimpi — CHANGES_REQUESTED** [review]
I don't think we should add Free Udemy Courses to this

**Comment by cullzie** [comment]
Ye I think it is best to leave this out. This tool is about coupons and enrolling in paid courses. 
Adding this means supporting it which might lead to more problems

**Pull request closed without merging**
