### PR TITLE
Fix bug where script doesn't scrape beyond first page

### PR DESCRIPTION
**Pull request by cullzie**
This became very clear once I had started working on some code around error handling. 
Basically because I initialised it stupidly it never got further then the first page even though it looked like it did

Apologies. Please accept this PR as payment :money_with_wings: 

Opening it as PR to master because it needs to be there ASAP

### CODE REVIEW

**Comment by fakeid30** [comment]
Accepted, when I tried I didn't catch it either because I didn't let it go past 1st page.

**Comment by cullzie** [comment]
Ye reading each link isn't something you do as it runs. It appears to be fine as the pages go up as well so I made bad assumptions :gun:

**Comment by fakeid30** [comment]
@cullzie I really appreciate your coding style. It's impeccable and very easy to read , what impressed me most is your usage of function annotation. I rarely see it.

**Comment by cullzie** [comment]
> @cullzie I really appreciate your coding style. It's impeccable and very easy to read , what impressed me most is your usage of function annotation. I rarely see it.

Cheers @fakeid30 but If I don't make it easy to read I won't know what I was doing in 2 days time :smile:

**Pull request merged**
