### PR TITLE
Updates and fixes for Alpha

### PR DESCRIPTION
**Pull request by cullzie**
# Description
Updates for better logging, handling currencies, documentation and some bug fixes

### CODE REVIEW

**Comment by cullzie** [comment]
@fakeid30 Merging these updates into Alpha. Let me know if there is any improvement with the checkout issue. Should be more logging now to help debug it. Its possible you have already enrolled in those courses. That was the only reason I was seeing checkout fail. The check for already enrolled courses should catch this but its possible there is a bug in there somewhere

**Comment by fakeid30** [comment]
@cullzie without debug 

```
nirjhor@nirjhor-summite14a11scs ~/D/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE (alpha)> python udemy_enroller.py
Loading existing settings
Loaded cookies from file
Loading existing course details
tutorialbar scraper is running
discudemy scraper is running
Page: 1 of 742 scraped from tutorialbar.com
Got 12 links from https://www.tutorialbar.com in 4.86 seconds
Page: 1 of 502 scraped from discudemy.com
Got 12 links from https://discudemy.com in 6.19 seconds
Successfully enrolled: https://www.udemy.com/course/ethical-hacking-capture-the-flag-walkthroughs-v3/
Successfully enrolled: https://www.udemy.com/course/kali-linux-essentials-for-ethical-hackers-beginners-guide/
Already enrolled in https://www.udemy.com/course/programming-network-applications-in-java/
Already enrolled in https://www.udemy.com/course/c-console-and-windows-forms-development-with-linq-adonet/
Already enrolled in https://www.udemy.com/course/python-complete-bootcamp-2019-learn-by-applying-knowledge/
Already enrolled in https://www.udemy.com/course/complete-progressive-web-app-bootcamp/
Already enrolled in https://www.udemy.com/course/data-science-real-world-projects-in-python-x/
Already enrolled in https://www.udemy.com/course/learn-javascript-from-beginner-to-advanced/
Successfully enrolled: https://www.udemy.com/course/certified-happiness-life-coach-specialist/
tutorialbar scraper is running
discudemy scraper is running
Page: 2 of 742 scraped from tutorialbar.com
Got 12 links from https://www.tutorialbar.com in 4.26 seconds
Page: 2 of 502 scraped from discudemy.com
Got 15 links from https://discudemy.com in 5.01 seconds
tutorialbar scraper is running
discudemy scraper is running
Page: 3 of 742 scraped from tutorialbar.com
Page: 3 of 502 scraped from discudemy.com
Got 8 links from https://discudemy.com in 2.16 seconds
Got 12 links from https://www.tutorialbar.com in 3.63 seconds
Unexpected exception: Malformed url passed in: https://bit.ly/3qihZmm
tutorialbar scraper is running
discudemy scraper is running
Page: 4 of 742 scraped from tutorialbar.com
Page: 4 of 502 scraped from discudemy.com
Got 0 links from https://discudemy.com in 2.66 seconds
Got 12 links from https://www.tutorialbar.com in 3.90 seconds
tutorialbar scraper is running
discudemy scraper is running
Page: 5 of 742 scraped from tutorialbar.com
Page: 5 of 502 scraped from discudemy.com
Stopping loop. We have reached max number of pages to scrape: 5
discudemy scraper complete
Got 0 links from https://discudemy.com in 2.40 seconds
Stopping loop. We have reached max number of pages to scrape: 5
tutorialbar scraper complete
Got 12 links from https://www.tutorialbar.com in 4.56 seconds
Unexpected exception: Malformed url passed in: https://bit.ly/3daIS7V
All scrapers complete

```

with debug

```
nirjhor@nirjhor-summite14a11scs ~/D/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE (alpha)> python udemy_enroller.py --debug
Enabled debug logging
Loading existing settings
Loaded cookies from file
Loading existing course details
tutorialbar scraper is running
discudemy scraper is running
Page: 1 of 742 scraped from tutorialbar.com
Received Link 1 : https://www.udemy.com/course/solidworks-2019-2-boyutlu-cizim-egitimi/?couponCode=ASKIDAEGITIMVAR
Received Link 2 : https://www.udemy.com/course/branding-masterclass-creating-professional-brand-imagery/?couponCode=FIVESTARS
Received Link 3 : https://www.udemy.com/course/agile-leadership/?couponCode=AGILE-LEADER-FEBFREE
Received Link 4 : https://www.udemy.com/course/sap-fico-free-video-tutorials-for-beginners-part-5/?couponCode=FEB21A
Received Link 5 : https://www.udemy.com/course/the-absolute-tools-guide-to-cyber-security-and-hacking/?couponCode=435E6D4F8888A26782B7
Received Link 6 : https://www.udemy.com/course/learn-html5-for-beginners-zero-to-hero-course-in-2021/?couponCode=FREECOURSE2021
Received Link 7 : https://www.udemy.com/course/acca-certifrs/?couponCode=EA9790296435E9A04D21
Received Link 8 : https://www.udemy.com/course/10-steps-for-a-successful-interview-get-the-job/?couponCode=36DC989B7345F3994185
Received Link 9 : https://www.udemy.com/course/comptia_a_plus/?couponCode=A632005AB82771F395A6
Received Link 10 : https://www.udemy.com/course/cqylzklh/?couponCode=1BCFCF029C9E6FA923DF
Received Link 11 : https://www.udemy.com/course/private-equity-leveraged-buyouts-lbos/?couponCode=THANKS4UREVIEWS
Received Link 12 : https://www.udemy.com/course/machine-learning-real-world-projects-in-python/?couponCode=DATA_SCIENTIST
Got 12 links from https://www.tutorialbar.com in 4.45 seconds
Received Link 1 : https://www.udemy.com/course/ethical-hacking-capture-the-flag-walkthroughs-v3/?couponCode=7E439D4EBDF21AA4D774
Received Link 2 : https://www.udemy.com/course/kali-linux-essentials-for-ethical-hackers-beginners-guide/?couponCode=ALLFREE
Received Link 3 : https://www.udemy.com/course/programming-network-applications-in-java/?couponCode=657680BC4251EFB7962E
Received Link 4 : https://www.udemy.com/course/c-console-and-windows-forms-development-with-linq-adonet/?couponCode=CSHARP_FEB_FREE_2
Received Link 5 : https://www.udemy.com/course/python-complete-bootcamp-2019-learn-by-applying-knowledge/?couponCode=FEBE02
Received Link 6 : https://www.udemy.com/course/complete-progressive-web-app-bootcamp/?couponCode=0BB4607C5C012C878168
Received Link 7 : https://www.udemy.com/course/data-science-real-world-projects-in-python-x/?couponCode=VALENTINE_SALE
Received Link 8 : https://www.udemy.com/course/learn-javascript-from-beginner-to-advanced/?couponCode=JS_FEB_FREE_2
Received Link 9 : https://www.udemy.com/course/certified-happiness-life-coach-specialist/?couponCode=HAPPYFREE
Received Link 10 : https://www.udemy.com/course/adobe-after-effects-learn-comic-book-animation/?couponCode=3C3F59F93ED8693C73A0
Received Link 11 : https://www.udemy.com/course/learn-to-build-8-android-widgets-in-2-hours/?couponCode=FREEFEB2
Received Link 12 : https://www.udemy.com/course/modern-javascript-es6-for-react-js/?couponCode=FREEFEB2
Page: 1 of 502 scraped from discudemy.com
Got 12 links from https://discudemy.com in 4.56 seconds
In cache: https://www.udemy.com/course/solidworks-2019-2-boyutlu-cizim-egitimi/?couponCode=ASKIDAEGITIMVAR
In cache: https://www.udemy.com/course/branding-masterclass-creating-professional-brand-imagery/?couponCode=FIVESTARS
In cache: https://www.udemy.com/course/agile-leadership/?couponCode=AGILE-LEADER-FEBFREE
In cache: https://www.udemy.com/course/sap-fico-free-video-tutorials-for-beginners-part-5/?couponCode=FEB21A
In cache: https://www.udemy.com/course/the-absolute-tools-guide-to-cyber-security-and-hacking/?couponCode=435E6D4F8888A26782B7
In cache: https://www.udemy.com/course/learn-html5-for-beginners-zero-to-hero-course-in-2021/?couponCode=FREECOURSE2021
In cache: https://www.udemy.com/course/acca-certifrs/?couponCode=EA9790296435E9A04D21
In cache: https://www.udemy.com/course/10-steps-for-a-successful-interview-get-the-job/?couponCode=36DC989B7345F3994185
In cache: https://www.udemy.com/course/comptia_a_plus/?couponCode=A632005AB82771F395A6
In cache: https://www.udemy.com/course/cqylzklh/?couponCode=1BCFCF029C9E6FA923DF
In cache: https://www.udemy.com/course/private-equity-leveraged-buyouts-lbos/?couponCode=THANKS4UREVIEWS
In cache: https://www.udemy.com/course/machine-learning-real-world-projects-in-python/?couponCode=DATA_SCIENTIST
In cache: https://www.udemy.com/course/ethical-hacking-capture-the-flag-walkthroughs-v3/?couponCode=7E439D4EBDF21AA4D774
In cache: https://www.udemy.com/course/kali-linux-essentials-for-ethical-hackers-beginners-guide/?couponCode=ALLFREE
In cache: https://www.udemy.com/course/programming-network-applications-in-java/?couponCode=657680BC4251EFB7962E
In cache: https://www.udemy.com/course/c-console-and-windows-forms-development-with-linq-adonet/?couponCode=CSHARP_FEB_FREE_2
In cache: https://www.udemy.com/course/python-complete-bootcamp-2019-learn-by-applying-knowledge/?couponCode=FEBE02
In cache: https://www.udemy.com/course/complete-progressive-web-app-bootcamp/?couponCode=0BB4607C5C012C878168
In cache: https://www.udemy.com/course/data-science-real-world-projects-in-python-x/?couponCode=VALENTINE_SALE
In cache: https://www.udemy.com/course/learn-javascript-from-beginner-to-advanced/?couponCode=JS_FEB_FREE_2
In cache: https://www.udemy.com/course/certified-happiness-life-coach-specialist/?couponCode=HAPPYFREE
In cache: https://www.udemy.com/course/adobe-after-effects-learn-comic-book-animation/?couponCode=3C3F59F93ED8693C73A0
In cache: https://www.udemy.com/course/learn-to-build-8-android-widgets-in-2-hours/?couponCode=FREEFEB2
In cache: https://www.udemy.com/course/modern-javascript-es6-for-react-js/?couponCode=FREEFEB2
tutorialbar scraper is running
discudemy scraper is running
Page: 2 of 742 scraped from tutorialbar.com
Received Link 1 : https://www.udemy.com/course/docker-container-course-for-beginners/?couponCode=FREEFEB2
Received Link 2 : https://www.udemy.com/course/flask-framework-complete-course-for-beginners/?couponCode=1EEF82A2991DCD5531E1
Received Link 3 : https://www.udemy.com/course/python-and-django-for-beginners/?couponCode=C695CBB291C75D5C5C7C
Received Link 4 : https://www.udemy.com/course/marketing-facebook-ads-leads-clientes-ventas-2020-2021-social-media/?couponCode=11FEB2021
Received Link 5 : https://www.udemy.com/course/marketing-digital-facebook-ads-ecommerce-ventas-online-dropshipping/?couponCode=11FEB2021
Received Link 6 : https://www.udemy.com/course/estrategias-pro-targeting-audiencia-facebook-ads-digital-social-media/?couponCode=11FEB2021
Received Link 7 : https://www.udemy.com/course/como-crear-y-configurar-tu-canal-de-youtube-marketing-video-movil/?couponCode=11FEB2021
Received Link 8 : https://www.udemy.com/course/wireshark-packet-analysis-and-ethical-hacking-core-skills/?couponCode=FEB2021
Received Link 9 : https://www.udemy.com/course/angular-10-fundamentos-8-app/?couponCode=FEBRERO
Received Link 10 : https://www.udemy.com/course/mindfulness-creating-amazing-life/?couponCode=MTCAAEXPFEB142021
Received Link 11 : https://www.udemy.com/course/microsoft-excel-masterclass-complete-and-concise/?couponCode=FEBX21
Received Link 12 : https://www.udemy.com/course/ultimate-tallyprime-with-gst-step-by-step-guide-2021/?couponCode=ULTIMATEFEB12
Received Link 13 : https://www.udemy.com/course/ultimate-adobe-photoshop-cc-masterclass-basics-to-advanced/?couponCode=FEB2021
Received Link 14 : https://www.udemy.com/course/lightworks-video-editing/?couponCode=009D53ED4E898DEFF839
Received Link 15 : https://www.udemy.com/course/blender-29-adobe-photoshop-3d-modeling-a-hobbit-door/?couponCode=COURSEROCKS
Page: 2 of 502 scraped from discudemy.com
Got 15 links from https://discudemy.com in 2.86 seconds
Received Link 1 : https://www.udemy.com/course/adobe-illustrator-cc-2020-masterclass/?couponCode=ILLUSTRATE
Received Link 2 : https://www.udemy.com/course/preparing-financial-statements/?couponCode=E5913935F3342DFEEB79
Received Link 3 : https://www.udemy.com/course/learn-the-most-common-conversations-in-egyptian-arabic/?couponCode=RATE_ME
Received Link 4 : https://www.udemy.com/course/learn-g-suite/?couponCode=TRY10FREE22104
Received Link 5 : https://www.udemy.com/course/create-your-step-by-step-90-day-strategic-plan/?couponCode=WGSTRATEGYFREE
Received Link 6 : https://www.udemy.com/course/geographical-information-system-with-arc-gis-google-earth/?couponCode=CIVILGIS
Received Link 7 : https://www.udemy.com/course/marketing-digital-facebook-ads-ecommerce-ventas-online-dropshipping/?couponCode=11FEB2021
Received Link 8 : https://www.udemy.com/course/learning-solidworks-for-students-engineers-and-designers/?couponCode=SOLIDMODELS
Received Link 9 : https://www.udemy.com/course/megacurso-bootstrap-4/?couponCode=FREEBOOTSTRAP4
Received Link 10 : https://www.udemy.com/course/micro-course-on-npv-and-irr/?couponCode=FEBFRC
Received Link 11 : https://www.udemy.com/course/microsoft-excel-from-beginner-to-advancedin-arabic/?couponCode=BDFE1F4B3F9420A7DA03
Received Link 12 : https://www.udemy.com/course/preparing-budgets-in-arabic/?couponCode=FC8E474796CC8B8F0470
Got 12 links from https://www.tutorialbar.com in 3.36 seconds
In cache: https://www.udemy.com/course/adobe-illustrator-cc-2020-masterclass/?couponCode=ILLUSTRATE
In cache: https://www.udemy.com/course/preparing-financial-statements/?couponCode=E5913935F3342DFEEB79
In cache: https://www.udemy.com/course/learn-the-most-common-conversations-in-egyptian-arabic/?couponCode=RATE_ME
In cache: https://www.udemy.com/course/learn-g-suite/?couponCode=TRY10FREE22104
In cache: https://www.udemy.com/course/create-your-step-by-step-90-day-strategic-plan/?couponCode=WGSTRATEGYFREE
In cache: https://www.udemy.com/course/geographical-information-system-with-arc-gis-google-earth/?couponCode=CIVILGIS
In cache: https://www.udemy.com/course/marketing-digital-facebook-ads-ecommerce-ventas-online-dropshipping/?couponCode=11FEB2021
In cache: https://www.udemy.com/course/learning-solidworks-for-students-engineers-and-designers/?couponCode=SOLIDMODELS
In cache: https://www.udemy.com/course/megacurso-bootstrap-4/?couponCode=FREEBOOTSTRAP4
In cache: https://www.udemy.com/course/micro-course-on-npv-and-irr/?couponCode=FEBFRC
In cache: https://www.udemy.com/course/microsoft-excel-from-beginner-to-advancedin-arabic/?couponCode=BDFE1F4B3F9420A7DA03
In cache: https://www.udemy.com/course/preparing-budgets-in-arabic/?couponCode=FC8E474796CC8B8F0470
In cache: https://www.udemy.com/course/docker-container-course-for-beginners/?couponCode=FREEFEB2
In cache: https://www.udemy.com/course/flask-framework-complete-course-for-beginners/?couponCode=1EEF82A2991DCD5531E1
In cache: https://www.udemy.com/course/python-and-django-for-beginners/?couponCode=C695CBB291C75D5C5C7C
In cache: https://www.udemy.com/course/marketing-facebook-ads-leads-clientes-ventas-2020-2021-social-media/?couponCode=11FEB2021
In cache: https://www.udemy.com/course/marketing-digital-facebook-ads-ecommerce-ventas-online-dropshipping/?couponCode=11FEB2021
In cache: https://www.udemy.com/course/estrategias-pro-targeting-audiencia-facebook-ads-digital-social-media/?couponCode=11FEB2021
In cache: https://www.udemy.com/course/como-crear-y-configurar-tu-canal-de-youtube-marketing-video-movil/?couponCode=11FEB2021
In cache: https://www.udemy.com/course/wireshark-packet-analysis-and-ethical-hacking-core-skills/?couponCode=FEB2021
In cache: https://www.udemy.com/course/angular-10-fundamentos-8-app/?couponCode=FEBRERO
In cache: https://www.udemy.com/course/mindfulness-creating-amazing-life/?couponCode=MTCAAEXPFEB142021
In cache: https://www.udemy.com/course/microsoft-excel-masterclass-complete-and-concise/?couponCode=FEBX21
In cache: https://www.udemy.com/course/ultimate-tallyprime-with-gst-step-by-step-guide-2021/?couponCode=ULTIMATEFEB12
In cache: https://www.udemy.com/course/ultimate-adobe-photoshop-cc-masterclass-basics-to-advanced/?couponCode=FEB2021
In cache: https://www.udemy.com/course/lightworks-video-editing/?couponCode=009D53ED4E898DEFF839
In cache: https://www.udemy.com/course/blender-29-adobe-photoshop-3d-modeling-a-hobbit-door/?couponCode=COURSEROCKS
tutorialbar scraper is running
discudemy scraper is running
Page: 3 of 742 scraped from tutorialbar.com
Received Link 1 : https://www.udemy.com/course/javascript-bootstrap-php-certification-for-beginners/?couponCode=YOUACCEL72448
Received Link 2 : https://www.udemy.com/course/setup-a-virtual-web-server-using-linode-or-digital-ocean/?couponCode=YOUACCEL72448
Received Link 3 : https://www.udemy.com/course/international-financial-reporting-standards-ifrs-k/?couponCode=9D403E64949A3BA8374C
Received Link 4 : https://www.udemy.com/course/bootstrap-jquery-certification-course-for-beginners/?couponCode=YOUACCEL72448
Received Link 5 : https://www.udemy.com/course/html-css-javascript-certification-course-for-beginners/?couponCode=YOUACCEL72448
Received Link 6 : https://www.udemy.com/course/learn-microsoft-teams/?couponCode=TRY10FREE22104
Received Link 7 : https://www.udemy.com/course/3daybusinessbreakthroughchallenge_jonathan_montoya/?couponCode=17884527F558EC659AC4
Received Link 8 : https://www.udemy.com/course/learn-basic-photoshop/?couponCode=TRY10FREE22104
Received Link 9 : https://www.udemy.com/course/nginx-apache-ssl-encryption-certification-course/?couponCode=YOUACCEL72448
Received Link 10 : https://www.udemy.com/course/html-javascript-bootstrap-certification-course/?couponCode=YOUACCEL72448
Received Link 11 : https://bit.ly/3qihZmm
Received Link 12 : https://www.udemy.com/course/solidworks-2019-3-boyutlu-kat-model-egitimi/?couponCode=ASKIDAEGITIMVAR
Got 12 links from https://www.tutorialbar.com in 3.41 seconds
Received Link 1 : https://www.udemy.com/course/power-query-m-language-with-specialize-in-web-scraping/?couponCode=DISCUDMY
Received Link 2 : https://www.udemy.com/course/investieren-in-immobilien-die-masterclass-fur-investoren/?couponCode=WEBSITE
Received Link 3 : https://www.udemy.com/course/learn-danish-for-beginners-intensive-danish-language-course/?couponCode=B1D50D95747837FD7314
Received Link 4 : https://www.udemy.com/course/time-management-m/?couponCode=TIMEMANAGEMENT
Received Link 5 : https://www.udemy.com/course/java-beginner-get-started-coding-with-java/?couponCode=12qw1
Page: 3 of 502 scraped from discudemy.com
Got 5 links from https://discudemy.com in 3.42 seconds
In cache: https://www.udemy.com/course/javascript-bootstrap-php-certification-for-beginners/?couponCode=YOUACCEL72448
In cache: https://www.udemy.com/course/setup-a-virtual-web-server-using-linode-or-digital-ocean/?couponCode=YOUACCEL72448
In cache: https://www.udemy.com/course/international-financial-reporting-standards-ifrs-k/?couponCode=9D403E64949A3BA8374C
In cache: https://www.udemy.com/course/bootstrap-jquery-certification-course-for-beginners/?couponCode=YOUACCEL72448
In cache: https://www.udemy.com/course/html-css-javascript-certification-course-for-beginners/?couponCode=YOUACCEL72448
In cache: https://www.udemy.com/course/learn-microsoft-teams/?couponCode=TRY10FREE22104
In cache: https://www.udemy.com/course/3daybusinessbreakthroughchallenge_jonathan_montoya/?couponCode=17884527F558EC659AC4
In cache: https://www.udemy.com/course/learn-basic-photoshop/?couponCode=TRY10FREE22104
In cache: https://www.udemy.com/course/nginx-apache-ssl-encryption-certification-course/?couponCode=YOUACCEL72448
In cache: https://www.udemy.com/course/html-javascript-bootstrap-certification-course/?couponCode=YOUACCEL72448
Unexpected exception: Malformed url passed in: https://bit.ly/3qihZmm
In cache: https://www.udemy.com/course/solidworks-2019-3-boyutlu-kat-model-egitimi/?couponCode=ASKIDAEGITIMVAR
In cache: https://www.udemy.com/course/power-query-m-language-with-specialize-in-web-scraping/?couponCode=DISCUDMY
In cache: https://www.udemy.com/course/investieren-in-immobilien-die-masterclass-fur-investoren/?couponCode=WEBSITE
In cache: https://www.udemy.com/course/learn-danish-for-beginners-intensive-danish-language-course/?couponCode=B1D50D95747837FD7314
In cache: https://www.udemy.com/course/time-management-m/?couponCode=TIMEMANAGEMENT
In cache: https://www.udemy.com/course/java-beginner-get-started-coding-with-java/?couponCode=12qw1
tutorialbar scraper is running
discudemy scraper is running
Page: 4 of 742 scraped from tutorialbar.com
Page: 4 of 502 scraped from discudemy.com
Got 0 links from https://discudemy.com in 2.40 seconds
Received Link 1 : https://www.udemy.com/course/learn-microsoft-office-365/?couponCode=TRY10FREE22104
Received Link 2 : https://www.udemy.com/course/excelparanegocios/?couponCode=A9C1618CEDDB2D81CE63
Received Link 3 : https://www.udemy.com/course/juniper-jn0-221-automation-and-devops-certification-practice/?couponCode=058161D801A3520170C3
Received Link 4 : https://www.udemy.com/course/quick-guide-setup-a-local-testing-server-using-wamp-or-mamp/?couponCode=YOUACCEL72448
Received Link 5 : https://www.udemy.com/course/fundamentals-of-network-security-b/?couponCode=1136F532C5AC8FC7511A
Received Link 6 : https://www.udemy.com/course/how-the-internet-works-the-web-development-process/?couponCode=YOUACCEL72448
Received Link 7 : https://www.udemy.com/course/theory-of-automata-and-computation/?couponCode=237827017E1C10B0AB08
Received Link 8 : https://www.udemy.com/course/how-to-draw-the-head/?couponCode=FREEBIESGLOBAL-P21
Received Link 9 : https://www.udemy.com/course/javascript-complete-real-time-production-usage-2019/?couponCode=FEB-VALENTINES-WEEK
Received Link 10 : https://www.udemy.com/course/most-essential-popular-excel-formulas-and-functions/?couponCode=MOSTFEB12
Received Link 11 : https://www.udemy.com/course/adobe-after-effects-learn-comic-book-animation/?couponCode=3C3F59F93ED8693C73A0
Received Link 12 : https://www.udemy.com/course/google-docs-master-course/?couponCode=TRY10FREE22104
Got 12 links from https://www.tutorialbar.com in 3.43 seconds
In cache: https://www.udemy.com/course/learn-microsoft-office-365/?couponCode=TRY10FREE22104
In cache: https://www.udemy.com/course/excelparanegocios/?couponCode=A9C1618CEDDB2D81CE63
In cache: https://www.udemy.com/course/juniper-jn0-221-automation-and-devops-certification-practice/?couponCode=058161D801A3520170C3
In cache: https://www.udemy.com/course/quick-guide-setup-a-local-testing-server-using-wamp-or-mamp/?couponCode=YOUACCEL72448
In cache: https://www.udemy.com/course/fundamentals-of-network-security-b/?couponCode=1136F532C5AC8FC7511A
In cache: https://www.udemy.com/course/how-the-internet-works-the-web-development-process/?couponCode=YOUACCEL72448
In cache: https://www.udemy.com/course/theory-of-automata-and-computation/?couponCode=237827017E1C10B0AB08
In cache: https://www.udemy.com/course/how-to-draw-the-head/?couponCode=FREEBIESGLOBAL-P21
In cache: https://www.udemy.com/course/javascript-complete-real-time-production-usage-2019/?couponCode=FEB-VALENTINES-WEEK
In cache: https://www.udemy.com/course/most-essential-popular-excel-formulas-and-functions/?couponCode=MOSTFEB12
In cache: https://www.udemy.com/course/adobe-after-effects-learn-comic-book-animation/?couponCode=3C3F59F93ED8693C73A0
In cache: https://www.udemy.com/course/google-docs-master-course/?couponCode=TRY10FREE22104
tutorialbar scraper is running
discudemy scraper is running
Page: 5 of 742 scraped from tutorialbar.com
Page: 5 of 502 scraped from discudemy.com
Stopping loop. We have reached max number of pages to scrape: 5
discudemy scraper complete
Got 0 links from https://discudemy.com in 2.30 seconds
Received Link 1 : https://www.udemy.com/course/ultimate-tallyprime-with-gst-step-by-step-guide-2021/?couponCode=ULTIMATEFEB12
Received Link 2 : https://www.udemy.com/course/use-infographics-to-grab-customers-attention/?couponCode=FEBPROMO
Received Link 3 : https://www.udemy.com/course/advanced-microsoft-excel-formulas-functions/?couponCode=ADVFEB12
Received Link 4 : https://www.udemy.com/course/docker-container-course-for-beginners/?couponCode=FREEFEB2
Received Link 5 : https://www.udemy.com/course/introduction-to-microservices-edyoda/?couponCode=FREEFEB2
Received Link 6 : https://www.udemy.com/course/flask-framework-complete-course-for-beginners/?couponCode=1EEF82A2991DCD5531E1
Received Link 7 : https://www.udemy.com/course/python-and-django-for-beginners/?couponCode=C695CBB291C75D5C5C7C
Received Link 8 : https://www.udemy.com/course/modern-javascript-es6-for-react-js/?couponCode=FREEFEB2
Received Link 9 : https://www.udemy.com/course/fundamentals-of-p-n-junction-diode/?couponCode=4BAA34E1B98F7AE486F1
Received Link 10 : https://www.udemy.com/course/learn-to-build-8-android-widgets-in-2-hours/?couponCode=FREEFEB2
Received Link 11 : https://www.udemy.com/course/learn-front-end-development/?couponCode=TRY10FREE22104
Received Link 12 : https://bit.ly/3daIS7V
Stopping loop. We have reached max number of pages to scrape: 5
tutorialbar scraper complete
Got 12 links from https://www.tutorialbar.com in 3.51 seconds
In cache: https://www.udemy.com/course/ultimate-tallyprime-with-gst-step-by-step-guide-2021/?couponCode=ULTIMATEFEB12
In cache: https://www.udemy.com/course/use-infographics-to-grab-customers-attention/?couponCode=FEBPROMO
In cache: https://www.udemy.com/course/advanced-microsoft-excel-formulas-functions/?couponCode=ADVFEB12
In cache: https://www.udemy.com/course/docker-container-course-for-beginners/?couponCode=FREEFEB2
In cache: https://www.udemy.com/course/introduction-to-microservices-edyoda/?couponCode=FREEFEB2
In cache: https://www.udemy.com/course/flask-framework-complete-course-for-beginners/?couponCode=1EEF82A2991DCD5531E1
In cache: https://www.udemy.com/course/python-and-django-for-beginners/?couponCode=C695CBB291C75D5C5C7C
In cache: https://www.udemy.com/course/modern-javascript-es6-for-react-js/?couponCode=FREEFEB2
In cache: https://www.udemy.com/course/fundamentals-of-p-n-junction-diode/?couponCode=4BAA34E1B98F7AE486F1
In cache: https://www.udemy.com/course/learn-to-build-8-android-widgets-in-2-hours/?couponCode=FREEFEB2
In cache: https://www.udemy.com/course/learn-front-end-development/?couponCode=TRY10FREE22104
Unexpected exception: Malformed url passed in: https://bit.ly/3daIS7V
All scrapers complete
nirjhor@nirjhor-summite14a11scs ~/D/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE (alpha)> 

```

Total enrolled course: 3

It broke on bitly (this is blocked in my country) but before that it only enrolled in 3 courses.

**Comment by cullzie** [comment]
Well at least it enrolled in something which is progress. The malformed URL is just something I put in because those bit.ly URLs won't resolve now. 
Overall I think it's looking more stable now. Just need to monitor it for the next few days and figure out any issues with it. 
Thanks @fakeid30 for taking a look

**Comment by fakeid30** [comment]
But it did not enroll to everything. Plus after first 3 it stopped enrolling.

**Comment by cullzie** [comment]
Ye it's not enrolling because it says they are already in the cache. I'll need to check with a clean account but I wasn't having any issues for enrollment.

**Pull request merged**
