### PR TITLE
Adding argparse 

### LINKED ISSUE #33: Create a toggle in settings.yaml that lets the script stop after pre-selected pages
[Implementing this closed PR in a modular way is ideal](https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/pull/11)

### PR DESCRIPTION
**Pull request by cullzie**
# Description

- Updating to accept CLI arguments. Max number of pages to scrape from tutorialbar.com: `max-pages= 5`

- Also added core script `udemy_enroller.py` which contains all logic related to argparse and running the script
For example now `udemy_enroller_chrome.py` simply calls the core methods in `udemy_enroller.py` with its browser arg

- Ability to pass `--browser=chrome` arg to core script and for it to generate the correct driver based on this string

- Updated CI to include macOS

**TODO: Create unittests**

Fixes #33 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Unittests passing
- [x] Run scripts via CLI with args passed and validated correct behaviour
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have added tests that prove my fix is effective or that my feature works (Optional)
- [x] New and existing unit tests pass locally with my changes (Optional)

### CODE REVIEW

**Comment by fakeid30** [comment]
@cullzie fantastic job, i think we should have a man page so that people can check the arguments. 

As it is now , `python udemy_enroller_firefox.py --max-pages=X` will work, right ? or is it `max_pages`?

Also, how do you like the new PR template ? is it too verbose ?

**Comment by cullzie** [comment]
> @cullzie fantastic job, i think we should have a man page so that people can check the arguments.
> 
> As it is now , `python udemy_enroller_firefox.py --max-pages=X` will work, right ? or is it `max_pages`?
> 
> Also, how do you like the new PR template ? is it too verbose ?

If you run with --help if should show the options available.  Are man pages not for system programs?

This is the current output of --help or -h command:
```
python udemy_enroller_chrome.py --help
usage: udemy_enroller_chrome.py [-h] [--browser {chrome,ff,opera,google-chrome,edge,internet_explorer,ie,firefox,chromium}] [--max-pages MAX_PAGES]

Udemy Enroller

optional arguments:
  -h, --help            show this help message and exit
  --browser {chrome,ff,opera,google-chrome,edge,internet_explorer,ie,firefox,chromium}
                        Browser to use for Udemy Enroller
  --max-pages MAX_PAGES
                        Max pages to scrape from tutorialbar.com

```

Ye it is `--max-pages` as it is and it should work for all the scripts

I like the PR template :+1:  Helps to have a checklist for checking everything is upto scratch

**Comment by fakeid30** [comment]
This seems like a good time to add a wiki

**Comment by cullzie** [comment]
Obviously the `--help` is a bit off it run from the helper scripts i.e `udemy_enroller_firefox.py` but if the goal is to move to a release on pypi we should only have one entrypoint which  would be `udemy_enroller.py`

**Comment by fakeid30** [comment]
Take a look at here , this seems like the ideal method to run this app in the future : https://pipxproject.github.io/pipx/

**Review by fakeid30 — APPROVED** [review]

**Pull request merged**
