### PR TITLE
Add requests to requirements

### PR DESCRIPTION
**Pull request by MustafaAmer-1**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests that prove my fix is effective or that my feature works (Optional)
- [ ] New and existing unit tests pass locally with my changes (Optional)

### CODE REVIEW

**Comment by fakeid30** [comment]
@MustafaAmer-1 Thank you for the PR, This will surely be useful. I am making an exception this time and accepting it in master. But from next time, please send PR against develop branch. Thank you.

**Comment by cullzie** [comment]
@fakeid30 @MustafaAmer-1 `requests` module is no longer required. We are using `aiohttp`. It shouldn't be in the requirements file. What is the reason for adding it back in?

**Comment by fakeid30** [comment]
@cullzie my bad, i reverted it. I forgot about aiohttp.

**Comment by cullzie** [comment]
@fakeid30 Its no problem. Wouldn't have any impact on anything :smile: 
Think we can remove `requirements.py` now that I've spotted it but that can be done another time

**Pull request merged**
