### PR TITLE
Add zipcode functionality

### PR DESCRIPTION
**Pull request by ethankrein**
This pull request is made in response to issue aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#4.

My interpretation of the problem was similar to pull request aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#5, however, there are a few key differences.

Instead of relying on the length of a user-inputted **zipcode** variable, I use a try block to input the zip code and simply pass if an exception states that the element need not be filled. This will make it more clear if an error is raised because the **zipcode** is wrong and allows for the 1 second sleep to only be done if a **zipcode** is required.

Additionally, solving the problem in this way means the formatting of the **zipcode** variable can be consistent with the **email** & **password** variable formats.  This is better than it being left blank in aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#5 for obvious reasons.

I also updated the README to reflect the new **zipcode** variable.

### CODE REVIEW

**Comment by diflartle** [comment]
That is a better solution than I had. I should learn some python!

**Comment by aapatre** [comment]
Hi, I will check if the code is valid for my region. Even though the HTML element ID for the 'zip code box-counterpart' is same in our region, we have a drop-down box instead of an <input> text-box.

**Comment by ethankrein** [comment]
> That is a better solution than I had. I should learn some python!

I actually quite liked how you implemented certain changes and I used your comments as they were clear. Without your pr I probably would not have noticed the button disabling itself, so thank you.

**Comment by aapatre** [comment]
This works perfectly! Approving it! Thank you all for your contribution; seriously touched by your response and the spirit to improve the code! Cheers! 🍻

**Pull request merged**
