### PR TITLE
moved the settings credentials to a json file

### PR DESCRIPTION
**Pull request by ponix4k**
i have moved the creds and wedriver settings to their own .json file and added info on the read me to eaplain why

### CODE REVIEW

**Comment by aapatre** [comment]
Hey man! Thanks a lot for your contribution, I really appreciate it! :)
But I've already made some major changes to the code, so there are conflicts with the branch. Also, json is indeed a good idea but the only issue is most beginners aren't familiar with JSON and currently our focus is to make it as beginner-friendly as possible.

**Comment by ethankrein** [comment]
> the only issue is most beginners aren't familiar with JSON and currently our focus is to make it as beginner-friendly as possible.

Might I suggest YAML? It's more friendly to the end user than JSON and is easily understood by beginners.

For a quick example, their site is even in YAML: https://yaml.org/

**Review by ethankrein — COMMENTED** [review]
While this commit can no longer be made due to conflicts, I would also argue that it was not fit for acceptance. This pr includes extreme changes without reason or documentation and was submitted with little care for the project overall.

**Comment by aapatre** [comment]
Thanks a lot, I will check YAML

**Comment by aapatre** [comment]
Don't be disheartened bruh, I bet you can contribute in some other way! The first time I tried to make this bot, it was a big mess too. Don't worry, and focus on making it more user friendly as of now. Closing the pull request.

**Pull request closed without merging**
