### PR TITLE
Adding stats at the end of run

### LINKED ISSUE #223: [FEATURE REQUEST] Add stats at end of run
**Describe the solution you'd like**
Add some information in tabular format at the end of a run

Could contain info such as:

- Number of courses enrolled
- Savings ($420 saved)
- Number of courses scraped
- Average enrol time
- Average scrape time
- Already enrolled count
- Coupon expired count

**Describe alternatives you've considered**
Plenty of libraries which print tables nicely in the terminal Eg. https://pypi.org/project/tabulate/

**Additional context**

### PR DESCRIPTION
**Pull request by kovarden**
# Description
Added dependency to Tabulate(https://pypi.org/project/tabulate/) for printing table in the terminal

Fixes #223

Stats about:
- Number of courses enrolled
- Money savings
- Number of courses scraped
- Average enrol time
- Average scrape time
- Already enrolled count
- Coupon expired count
were added

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Run locally and checking the stats propriety on Win10

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests that prove my fix is effective or that my feature works (Optional)
- [ ] New and existing unit tests pass locally with my changes (Optional)

### CODE REVIEW

**Comment by cullzie** [comment]
Thanks for contributing @kovarden and apologies for the delay in looking at this.

There seems to be a lot of changes on develop which this commit is changing back. Can you please update your branches and make sure you are not changing anything you haven't touched. Thanks

**Comment by fakeid30** [comment]
@kovarden any update on this?

**Comment by cullzie** [comment]
@kovarden Any progress on this? There have been some stats changes merged already. If you could have a look and see if there is anything in this PR that we could include that would be great. 
Otherwise we will close it at the end of September. Thanks

**Comment by cullzie** [comment]
Closing due to inactivity. 
@kovarden If you want to re-submit we are happy to review again.

**Pull request closed without merging**
