### PR TITLE
Update udemy_enroller_vanilla.py

### PR DESCRIPTION
**Pull request by jimpallomeni**
After the first time, I don't need it to go through all the pages of tutorialbar.com. Most of the coupons past page 5 to 10 are expired or no good. I put this in to only go through the first 6 pages and then stop. This was a quick edit, it would probably be better to put this in the settings.txt.

### CODE REVIEW

**Comment by fakeid30** [comment]
This looks like good change. @aapatre can we introduce unit test and / or CI/CD  so we know changes work before merging ? https://www.lambdatest.com/blog/automated-testing-pipeline-with-gitlab-ci-cd-and-selenium/ this is a good resource on how to set it up.

**Comment by ethankrein** [comment]
The idea is good, but setting a static page in the code is less than ideal. Adding a page to stop on as a setting as @jimpallomeni suggested is probably the best way to implement this.

Instead of specifying a page the setting could be whether to continually try new pages or break after it detects x number of courses haven't worked.

**Comment by aapatre** [comment]
Hi guys, I noticed the pull request yesterday but was thinking about ways to add more improvements to it. Not really familiar with unit test or the other mentioned terms. Would search them up though. 

Also, I'm taking a break from this project at least for now, due to my other projects and academics so I wouldn't be adding much for a while. But, if you guys wish to improve it, you are most welcome to! 🥂🙌

I will be participating in the discussion whenever possible.

It began as my personal project to make my routine of enrolling easier and I decided to post it on GitHub/Reddit for others who may be interested. So it makes me really happy to see you guys participating, fixing and improving the code. :)

Cheers & Good Luck Guys!

**Comment by fakeid30** [comment]
@jimpallomeni I am closing this PR because we are trying to be modular with our changes and we will likely add this option in settings.yaml and . Your fix is appreciated, maybe if you want to further work on this , fetch our latest changes and resubmit this PR as a toggle, and not hardcoded like this. Thank you for understanding.

**Pull request closed without merging**
