### PR TITLE
Merging master into develop

### PR DESCRIPTION
**Pull request by cullzie**
Think this is the reason we're seeing these changes in the PR
Merging master into develop so we are in sync

### CODE REVIEW

**Comment by fakeid30** [comment]
Will need to create a changelog and cut a release for this but otherwise I agree.

**Comment by fakeid30** [comment]
I think the only thing we added that is worth adding to is 

* fixed CI

**Review by fakeid30 — APPROVED** [review]
Will need to create a changelog and cut a release for this but otherwise I agree.

**Comment by cullzie** [comment]
@fakeid30 This is just merging master into the develop branch so its in sync. We shouldn't need a release. 
Any code that has been added on master is around development/metrics. Nothing a user would be concerned with

**Comment by fakeid30** [comment]
Oh i read it wrong . So yah merging.

**Comment by cullzie** [comment]
@fakeid30 Thanks :+1:

**Pull request merged**
