### PR TITLE
Fixed idownloadcoupon scraping

### LINKED ISSUE #432: [BUG] idownloadcoupon scraper error
**Describe the bug**
This is the error log.
```
Error while running idownloadcoupon scraper: list index out of range
Traceback (most recent call last):
  File "Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/udemy_enroller/scrapers/base_scraper.py", line 90, in wrapper
    response = await func(self)
  File "Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/udemy_enroller/scrapers/idownloadcoupon.py", line 36, in run
    links = await self.get_links()
  File "Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/udemy_enroller/scrapers/idownloadcoupon.py", line 54, in get_links
    udemy_links = await self.gather_udemy_course_links(course_links)
  File "Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/udemy_enroller/scrapers/idownloadcoupon.py", line 104, in gather_udemy_course_links
    for link in await asyncio.gather(*map(self.get_udemy_course_link, courses))
  File "Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/udemy_enroller/scrapers/idownloadcoupon.py", line 93, in get_udemy_course_link
    return cls.validate_coupon_url(urllib.parse.unquote(urls[1]))
IndexError: list index out of range
```

**To Reproduce**
1. Clone the repo or install it from pypi.
2. Install dependencies.
3. cd to repo directory.
4. `python run_enroller.py`
5. See error

**Expected behavior**
All scrapers works fine.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version 4.1.3

### PR DESCRIPTION
**Pull request by samin-irtiza**
# Description

Fixed idownloadcoupon scraping by redirecting redeem button url manually and parsing the redirected udemy link with the coupon code.

Fixes #432 

## Type of change
Added a new function in http_utils.py called http_get_no_redirect that doesn't follow redirected url
Modified idownloadcoupon.py file and function called get_udemy_course_link. changed the url parsing code.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] Running the script in idownloadcoupon only mode by running `python.exe run_enroller.py --idownloadcoupon`

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests that prove my fix is effective or that my feature works (Optional)
- [ ] New and existing unit tests pass locally with my changes (Optional)

### CODE REVIEW

**Comment by samin-irtiza** [comment]
Hi,
I haven't used 'black' to format code before. trying to patch provided by restyled fails probably because of [this open issue ](https://github.com/psf/black/issues/2542) involving VSCode. That is why I haven't pushed code styling commit to the PR.

**Comment by cullzie** [comment]
Hey @samin-irtiza 
Thanks for the PR.
I think this could be added to the existing http_get method with an argument like `redirect=True` being the default. In cases where we don't want the redirect we can pass `redirect=False`

**Comment by samin-irtiza** [comment]
Hi @cullzie
Thanks for the feedback. I always try not to modify existing code as much as possible in a PR that's why I created the new method.

**Comment by cullzie** [comment]
Hey @samin-irtiza, The problem at the moment is there are too many diffs showing in this PR meaning its hard to see the actual changes. 
I think the only change you made was to add in that method but we could make the change in maybe 2-3 lines if we update the existing method to accept redirect param similar to how it takes headers and then modifying the specific scraper with the issue to pass redirect=false.
If you run black and isort it should resolve the majority of the diffs that are showing here.

**Comment by cullzie** [comment]
@samin-irtiza Can you please tidy up this PR to only show changes you made. At the moment everything is showing up as changed. Thanks

**Comment by samin-irtiza** [comment]
Hi @cullzie, I linted the code with black to tidy it up, but that seems to have caused more changes. Not sure what else I can do.

**Comment by fakeid30** [comment]
আমার কাছে ঠিকই লাগছে, আশা করি কালজি আপনার চেঞ্জ অ্যাক্সেপ্ট করবে।  @samin-irtiza

**Comment by cullzie** [comment]
Ok thanks @samin-irtiza 
I will merge since it will get reformatted at another stage if there is an issue.
Thanks for your contribution 🦖

**Pull request merged**
