### PR TITLE
Fixes for comidoc API

### PR DESCRIPTION
**Pull request by cullzie**
# Description

Update to comidoc scraper so that it doesn't error out on empty response
API had changed as well changes have been made to address that

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Ran locally. Getting links from the comidoc endpoint now. Added logging to show if the response is empty instead of erroring out

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests that prove my fix is effective or that my feature works (Optional)
- [x] New and existing unit tests pass locally with my changes (Optional)

### CODE REVIEW

**Comment by fakeid30** [comment]
Comidoc still failing in CI . Shall we just remove comidoc ?

**Comment by cullzie** [comment]
> Comidoc still failing in CI . Shall we just remove comidoc ?

Issue in CI is the user failing to login still:

```
Closing browser
Traceback (most recent call last):
  File "udemy_enroller.py", line 120, in <module>
    main()
  File "udemy_enroller.py", line 116, in main
    run(args.browser, tutorialbar_enabled, comidoc_enabled, args.max_pages)
  File "udemy_enroller.py", line 57, in run
    redeem_courses(dm.driver, settings, tutorialbar_enabled, comidoc_enabled, max_pages)
  File "/Users/runner/work/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/runner.py", line 89, in redeem_courses
    _redeem_courses(driver, settings, scrapers)
  File "/Users/runner/work/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/runner.py", line 32, in _redeem_courses
    udemy_actions.login()  # login once outside while loop
  File "/Users/runner/work/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/udemy.py", line 70, in login
    WebDriverWait(self.driver, 10).until(
  File "/Users/runner/Library/Caches/pypoetry/virtualenvs/automatic-udemy-course-enroller-get-paid-u-wJYs_73W-py3.8/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

Error: Process completed with exit code 1.
```

**Comment by fakeid30** [comment]
ok i messaged @aapatre , he will change the account ASAP

**Comment by fakeid30** [comment]
```
✖ 1 Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE git:(develop) ❯❯❯ python udemy_enroller.py --comidoc --browser=ff
Loading existing settings
[WDM] - Driver [/home/nirjhor/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
tutorialbar scraper disabled
comidoc scraper is running
Closing browser
Traceback (most recent call last):
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/udemy_enroller.py", line 120, in <module>
    main()
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/udemy_enroller.py", line 116, in main
    run(args.browser, tutorialbar_enabled, comidoc_enabled, args.max_pages)
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/udemy_enroller.py", line 57, in run
    redeem_courses(dm.driver, settings, tutorialbar_enabled, comidoc_enabled, max_pages)
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/runner.py", line 89, in redeem_courses
    _redeem_courses(driver, settings, scrapers)
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/runner.py", line 36, in _redeem_courses
    udemy_course_links = loop.run_until_complete(scrapers.run())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/scrapers/manager.py", line 28, in run
    await asyncio.gather(*map(lambda sc: sc.run(), enabled_scrapers)),
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/scrapers/base_scraper.py", line 65, in wrapper
    response = await func(self)
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/scrapers/comidoc.py", line 52, in run
    return await self.get_links()
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/scrapers/comidoc.py", line 56, in get_links
    data = await self.get_data()
  File "/home/nirjhor/PycharmProjects/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/core/scrapers/comidoc.py", line 98, in get_data
    data = json.loads(data)["data"]["coupons"]
TypeError: 'NoneType' object is not subscriptable

```

Seeing issue from this morning in comidoc again :(

**Comment by cullzie** [comment]
@fakeid30 Ye I know. I have another fix but if it changes again I don't think its worth supporting comidoc until it is stable.

**Pull request merged**
