### PR TITLE
Extracting core logic and add threading to course fetch on tutorialba…

### PR DESCRIPTION
**Pull request by cullzie**
…r.com

Hey @aapatre 
First off thanks for creating this tool :) 

This review is just to extract the core logic from the scripts into a reusable object.

It should make the creation of scripts for new browsers more straightforward:
```
    # firefox runner
    enroller = UdemyEnroller("firefox", settings_file="settings.yaml")
    enroller.run()
   
    # edge runner
    enroller = UdemyEnroller("edge", settings_file="settings.yaml")
    enroller.run()
```

The supported browsers are in `_init_browser` method 

I also extracted the fetching of links to use threading which greatly improves the speed at which we can loop through the courses
This is the method in question `gather_course_links`

There is also now extraction of the last page available so the while loop will terminate when the pages are exhausted

I am on linux at the moment and was only able to test out that chrome is working with the extracted logic. Hence I have only update the `udemy_enroller_chrome.py` script

Any questions let me know

### CODE REVIEW

**Review by ethankrein — COMMENTED** [review]
There's a lot of small things going on here that I quite like in addition to the core logic and threading.

* `self.udemy_logged_in` is a very nice way to have the login triggered. 
* The method of getting the last page is also done well.

In my opinion, those two changes and the addition of threading are perfect candidates for being pulled. However, at least at the moment, I don't believe everything should be consolidated to core logic. This project was initially built in a similar manner to that, but across browsers there are still some compatibility issues that need to be worked out. In addition to that, we also have project ideas in the pipeline that would need to be re-evaluated.

None of this is to say that I'm against what you've worked on, but I do think it will take some deliberation amongst the maintainers to decide how to proceed.

**Comment by fakeid30** [comment]
I'm with @ethankrein here. The threading is good but consolidating all changes into a single logic will have issues further down the line until we can figure out how to install the geckodriver automatically (ideally), plus some other features we were discussing. 

If not , we need to tell the users to download and install geckodriver prior to running. 

I am 50-50 on the changes. @aapatre what do you think?

**Comment by cullzie** [comment]
@ethankrein and @fakeid30 
Ye these are very valid points. These changes kind of snowballed for me and I figured I'd open the PR just to see if any of the changes were of interest. 
I think it would be better to split it down into separate improvements personally. Just need some direction on what the useful parts are for the project

Off topic now but what version of python is this originally written in? What are the python versions it should support?

**Comment by aapatre** [comment]
Thanks a lot for your contribution and feedback @cullzie 🥂
The threading implementation is indeed superb! But, due to compatibility issues across browsers, we can't add the browser selection features yet. (as mentioned by @ethankrein )

The earliest version involved manual webdriver setup but since our ultimate goal is to make the bot as user-friendly as possible, I added the webdriver manager and we need to fix compatibility issues now so that a single script can support all browsers.

I suggest you to send another PR for the threading features in all browsers (if possible) and I will accept the changes. :)

PS: If you are participating in the Hacktoberfest please mention it in the PR, so that I can add **hacktober-accepted** label to it.

**Comment by cullzie** [comment]
@aapatre Ye I can separate the threading logic into each script. I'll have a look at this and send on the PR

I realised its python 3.8 in from the README (Don't know how I missed it before :man_facepalming:)
Perhaps since it is in python 3 it might be possible to leverage asyncio but if you are looking to support dinosaurs (me included at times) in python 2 threading is the way to go.

**Comment by aapatre** [comment]
No worries, good luck! 🤝

**Comment by cullzie** [comment]
Closing the PR as agreed

Outcomes:
- Add threading logic into each script and open new PR

**Pull request closed without merging**
