### PR TITLE
Select State/Province from dropdown when needed to proceed with checkout

### LINKED ISSUE #143: Adding a feature to the script to ask the State/Territory in India [FEATURE REQUEST]
In India ,While enrolling Udemy is requesting for the "State/Union Territory" we live for enrollment,so instead of the zipcode pls consider to add this feature in the upcoming releases

### PR DESCRIPTION
**Pull request by cullzie**
# Description

Was finally able to get VPN working and test this with Indian ip
Existing code works in countries that don't require state/province

Fixes #143 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested and working with Indian account/ip
- [x] Tested and working with normal account

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests that prove my fix is effective or that my feature works (Optional)
- [x] New and existing unit tests pass locally with my changes (Optional)

### CODE REVIEW

**Comment by fakeid30** [comment]
This is getting timeout for me : 
```

✖ 130 Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE git:(dev_state) ❯❯❯ python udemy_enroller.py --browser=firefox --max-pages=10 --cache-hits=12
Loading existing settings
[WDM] - Driver [/home/nirjhor/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
Please Wait: Getting the course list from tutorialbar.com...
Page: 1 of 624 scraped
Received Link 1 : https://www.udemy.com/course/python-para-todos/?couponCode=PYTHON3
Received Link 2 : https://www.udemy.com/course/create-nodejs-app-with-express-socket-io-and-mongodb/?couponCode=DD280A29877AA7C1110E
Received Link 3 : https://www.udemy.com/course/reiki-complete-certification-energy-healing-crystal-master-shaman-pet/?couponCode=REIKI4FREE
Received Link 4 : https://www.udemy.com/course/english-grammar-course-tenses-structures/?couponCode=DECEMBERFIRST
Received Link 5 : https://www.udemy.com/course/media-training-how-to-speak-to-the-news-media-effectively/?couponCode=7D3B4DD04EA5C667B2E7
Received Link 6 : https://www.udemy.com/course/the-complete-basic-computer-course-master-using-computer/?couponCode=NEWYEARGIFT
Received Link 7 : https://www.udemy.com/course/vuejs-and-firebase-build-an-ios-and-android-chat-app/?couponCode=AE7FB3C83F0DEC728911
Received Link 8 : https://www.udemy.com/course/the-complete-business-marketing-course/?couponCode=4C8BB5A47B8F40D5A704
Received Link 9 : https://www.udemy.com/course/how-to-play-piano-go-from-a-beginnerintermediate-to-a-pro/?couponCode=3FE0207D72B3E9F800C5
Received Link 10 : https://www.udemy.com/course/basic-industrial-spill-contingency-exercise/?couponCode=FREEGAMIFIEDOSCE3
Received Link 11 : https://www.udemy.com/course/complete-progressive-web-app-bootcamp/?couponCode=472E3321D1E1C4D50193
Received Link 12 : https://www.udemy.com/course/debuter-avec-le-display-sur-google-ads-youtube-ads/?couponCode=FREE-DEC
Course language not wanted: Spanish
Timeout on link: https://www.udemy.com/course/create-nodejs-app-with-express-socket-io-and-mongodb/?couponCode=DD280A29877AA7C1110E
^CExiting the script

```
and then 

```
✖ 130 Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE git:(dev_state) ❯❯❯ python udemy_enroller.py --browser=firefox --max-pages=10 --cache-hits=12
Loading existing settings
[WDM] - Driver [/home/nirjhor/.wdm/drivers/geckodriver/linux64/v0.28.0/geckodriver] found in cache
Please Wait: Getting the course list from tutorialbar.com...
Page: 1 of 624 scraped
Received Link 1 : https://www.udemy.com/course/python-para-todos/?couponCode=PYTHON3
Received Link 2 : https://www.udemy.com/course/vuejs-and-firebase-build-an-ios-and-android-chat-app/?couponCode=AE7FB3C83F0DEC728911
Received Link 3 : https://www.udemy.com/course/complete-progressive-web-app-bootcamp/?couponCode=472E3321D1E1C4D50193
Received Link 4 : https://www.udemy.com/course/create-nodejs-app-with-express-socket-io-and-mongodb/?couponCode=DD280A29877AA7C1110E
Received Link 5 : https://www.udemy.com/course/reiki-complete-certification-energy-healing-crystal-master-shaman-pet/?couponCode=REIKI4FREE
Received Link 6 : https://www.udemy.com/course/media-training-how-to-speak-to-the-news-media-effectively/?couponCode=7D3B4DD04EA5C667B2E7
Received Link 7 : https://www.udemy.com/course/the-complete-basic-computer-course-master-using-computer/?couponCode=NEWYEARGIFT
Received Link 8 : https://www.udemy.com/course/english-grammar-course-tenses-structures/?couponCode=DECEMBERFIRST
Received Link 9 : https://www.udemy.com/course/basic-industrial-spill-contingency-exercise/?couponCode=FREEGAMIFIEDOSCE3
Received Link 10 : https://www.udemy.com/course/debuter-avec-le-display-sur-google-ads-youtube-ads/?couponCode=FREE-DEC
Received Link 11 : https://www.udemy.com/course/the-complete-business-marketing-course/?couponCode=4C8BB5A47B8F40D5A704
Received Link 12 : https://www.udemy.com/course/how-to-play-piano-go-from-a-beginnerintermediate-to-a-pro/?couponCode=3FE0207D72B3E9F800C5
In cache: https://www.udemy.com/course/python-para-todos/?couponCode=PYTHON3


```

**Comment by cullzie** [comment]
Is this with Indian ip or in general? I'm still having issues with my vpn so not sure when I'll get to test this properly.

**Comment by fakeid30** [comment]
I tried with indian ip. I actually did not try with vpn off.

After this hung I switched back to normal dev branch and tested without vpn. 

Guess I'll test tomorrow and see if the issue is on my end or what.

**Comment by cullzie** [comment]
@fakeid30 Was finally able to get my VPN working. Issue was we were not allowing the enroll now button to become clickable after selecting from the dropdown. Should be working now

**Comment by fakeid30** [comment]
@cullzie works now . Thanks.

**Pull request merged**
